version: '3'

services:

  db:
    image: 'mariadb'
    container_name: db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PI
      - MYSQL_USER=root
    ports:
      - "3306:3306"

  myapp-main:
    image: pi
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
